// Auto-generated by tools/add_cert.py -- edit manifest.json (titles/links), then rerun --rescan.
window.CERTS = [
  {
    "file": "Intel AI for Manufacturing - Intel x GTU.jpg",
    "title": "Intel AI for Manufacturing - Intel x GTU",
    "href": "https://drive.google.com/file/d/12h5xLpPGBtatQeVD58qBLEJQSmp-xq89/view"
  },
  {
    "file": "Microsoft Elevate x GTU - 12 Week Internship.jpg",
    "title": "Microsoft Elevate x GTU - 12 Week Internship",
    "href": "https://drive.google.com/file/d/1tkj5wg-F0-4ZDXphDuqYg5CqXSY9AYNj/view"
  },
  {
    "file": "CPTE - Certified Penetration Testing Engineer.jpg",
    "title": "CPTE - Certified Penetration Testing Engineer",
    "href": "https://drive.google.com/file/d/14GhWWm-W61zGIhziyXJTzulcRXn3sfe9/view"
  },
  {
    "file": "IELTS - Overall 7.0 - CEFR C1.jpg",
    "title": "IELTS - Overall 7.0 - CEFR C1",
    "href": "https://drive.google.com/file/d/1xTo7HGPQPAFa1i58keIJwbAopnTyXBPq/view"
  },
  {
    "file": "Anthropic - Claude 101.jpg",
    "title": "Anthropic - Claude 101",
    "href": "https://drive.google.com/file/d/1hs8cF4RXfaNLIibJJUSpAOn7w8fIDBL5/view"
  },
  {
    "file": "Anthropic - Claude Code 101.jpg",
    "title": "Anthropic - Claude Code 101",
    "href": "https://drive.google.com/file/d/1L_1ZcNdsJ73uY7OY3d3agx1ItT34avP1/view"
  },
  {
    "file": "Anthropic - Intro to MCP.jpg",
    "title": "Anthropic - Intro to MCP",
    "href": "https://drive.google.com/file/d/1u6DrHpu-uKMpHJGQNddKVOzzM-MeSB9k/view"
  },
  {
    "file": "AI Fundamentals.jpg",
    "title": "AI Fundamentals",
    "href": ""
  },
  {
    "file": "AI for App Building.jpg",
    "title": "AI for App Building",
    "href": ""
  },
  {
    "file": "AI for Brainstorming and Planning.jpg",
    "title": "AI for Brainstorming and Planning",
    "href": ""
  },
  {
    "file": "AI for Content Creation.jpg",
    "title": "AI for Content Creation",
    "href": ""
  },
  {
    "file": "AI for Data Analysis.jpg",
    "title": "AI for Data Analysis",
    "href": ""
  },
  {
    "file": "AI for Research and Insight.jpg",
    "title": "AI for Research and Insight",
    "href": ""
  },
  {
    "file": "AI for Writing and Communicating.jpg",
    "title": "AI for Writing and Communicating",
    "href": ""
  },
  {
    "file": "Google AI Professional Certificate.jpg",
    "title": "Google AI Professional Certificate",
    "href": ""
  }
];
