"""Convert a certificate PDF to a high-quality JPEG and update the Vault manifest.

Usage:
    python add_cert.py --add "C:/path/to/certificate.pdf" --drive "https://drive.google.com/..."
    python add_cert.py --rescan

--add renders page 1 of the PDF into ../certificates/<name>.jpg (the filename
is the caption shown on the site) and records the --drive proof link in the
manifest. --rescan just rescans the certificates folder -- use it after
manually dropping in (or deleting) a .jpg/.jpeg/.png/.webp, or after editing
titles/links in manifest.json.

The website reads certificates/manifest.js at load time and builds the Vault
deck from it, so whatever this script writes is what the site shows.

Requires:  pip install -r requirements.txt   (pypdfium2, pillow)
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # raj-portfolio/
CERT_DIR = ROOT / "certificates"
MANIFEST_JSON = CERT_DIR / "manifest.json"     # human-editable metadata (titles, proof links)
MANIFEST_JS = CERT_DIR / "manifest.js"         # generated from the JSON; loaded by the site
IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def safe_name(text):
    # keep the human-readable name; strip only characters illegal in filenames/URLs
    name = re.sub(r'[<>:"/\|?*#%]+', "", text)
    return re.sub(r"\s+", " ", name).strip() or "certificate"


def pretty_title(stem):
    # the filename (minus extension) IS the caption shown on the site
    return re.sub(r"\s+", " ", stem).strip()


def load_manifest():
    if MANIFEST_JSON.exists():
        return json.loads(MANIFEST_JSON.read_text(encoding="utf-8"))
    return []


def rescan(entries, new_meta=None):
    """Keep existing entries (and their order/metadata) for files still on disk;
    append any images not yet in the manifest."""
    on_disk = sorted(p.name for p in CERT_DIR.iterdir() if p.suffix.lower() in IMG_EXTS)
    kept = [e for e in entries if e.get("file") in on_disk]
    for e in kept:  # re-adding a cert with --title/--drive updates its entry
        meta = (new_meta or {}).get(e["file"], {})
        if meta.get("title"):
            e["title"] = meta["title"]
        if meta.get("href"):
            e["href"] = meta["href"]
    have = {e["file"] for e in kept}
    for f in on_disk:
        if f not in have:
            meta = (new_meta or {}).get(f, {})
            kept.append({
                "file": f,
                "title": meta.get("title") or pretty_title(Path(f).stem),
                "href": meta.get("href", ""),
            })
    return kept


def write_manifest(entries):
    MANIFEST_JSON.write_text(
        json.dumps(entries, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    MANIFEST_JS.write_text(
        "// Auto-generated by tools/add_cert.py -- edit manifest.json (titles/links), then rerun --rescan.\n"
        "window.CERTS = " + json.dumps(entries, indent=2, ensure_ascii=True) + ";\n",
        encoding="utf-8")


def convert(pdf_path, name, page, width, quality):
    import pypdfium2 as pdfium

    pdf = pdfium.PdfDocument(str(pdf_path))
    pg = pdf[page - 1]
    img = pg.render(scale=width / pg.get_width()).to_pil().convert("RGB")
    pdf.close()  # don't keep the source PDF locked
    out = CERT_DIR / (name + ".jpg")
    img.save(out, quality=quality, optimize=True)
    return out, img.size


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--add", metavar="PDF", help="path to the certificate PDF to convert")
    ap.add_argument("--title", help="caption shown on the card (default: the filename itself)")
    ap.add_argument("--drive", default="", help="proof URL the card links to (e.g. Google Drive share link)")
    ap.add_argument("--name", help="output filename without extension (default: the PDF's own name) — this is also the caption shown on the site")
    ap.add_argument("--page", type=int, default=1, help="PDF page to render (default 1)")
    ap.add_argument("--width", type=int, default=1600, help="output width in px (default 1600)")
    ap.add_argument("--quality", type=int, default=85, help="JPEG quality 1-95 (default 85)")
    ap.add_argument("--rescan", action="store_true", help="only rescan the folder and refresh the manifest")
    args = ap.parse_args()

    if not args.add and not args.rescan:
        ap.error('use --add "path/to/certificate.pdf" (optionally with --drive "url"), or --rescan')

    CERT_DIR.mkdir(exist_ok=True)
    new_meta = {}

    if args.add:
        pdf_path = Path(args.add)
        if not pdf_path.exists():
            sys.exit("error: file not found: " + str(pdf_path))
        name = args.name or safe_name(pdf_path.stem)
        out, size = convert(pdf_path, name, args.page, args.width, args.quality)
        kb = out.stat().st_size // 1024
        print("converted: {} -> {}  {}x{}  {} KB".format(pdf_path.name, out.relative_to(ROOT), size[0], size[1], kb))
        new_meta[out.name] = {"title": args.title, "href": args.drive}

    entries = rescan(load_manifest(), new_meta)
    write_manifest(entries)
    print("manifest updated: {} certificate(s)".format(len(entries)))
    for i, e in enumerate(entries, 1):
        print("  {}. {}  --  {}{}".format(i, e["file"], e["title"], "  [no proof link]" if not e.get("href") else ""))


if __name__ == "__main__":
    main()
